enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "^1.0.1"
  eth-block-tracker@*:
    dependencies:
      "@babel/core": ^7.18.13
  jest-environment-miniflare@*:
    dependencies:
      "@miniflare/r2": ^2.7.1

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
